version: '3.8'
services:

  app-server:
    container_name: app
    image: app_img
    depends_on:
      - redis
      - aws
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=LOCAL
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - AWS_REGION=us-east-1
      - AWS_API_VERSION=2006-03-01
      - AWS_S3_BUCKET_NAME=m3
      - AWS_S3_ENDPOINT=http://aws:4566
      - AWS_ACCESS_KEY_ID=FAKE
      - AWS_SECRET_ACCESS_KEY=FAKE
      - GIT_ACCESS_TOKEN=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
    logging:
      options:
        max-size: 50m

  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  aws:
    container_name: aws
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports:
      - 4566-4583:4566-4583
    volumes:
      - "localstack-volume:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack-volume: {}
