version: '3.8'
services:

  app:
    container_name: app
    image: app_img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - aws
    links:
      - sls
    environment:
      - NODE_ENV=LOCAL
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_REGION=us-east-1
      - AWS_API_VERSION=2006-03-01
      - AWS_S3_HOST=http://aws:4566
      - AWS_S3_BUCKET=m3-api
      - AWS_ACCESS_KEY_ID=FAKE
      - AWS_SECRET_ACCESS_KEY=FAKE
      - GIT_API_BASE_URL=https://api.github.com
      - GIT_ACCESS_TOKEN=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
    logging:
      options:
        max-size: 50m

  sls:
    container_name: sls
    image: sls_img
    build:
      context: ./
      dockerfile: sls.Dockerfile
    depends_on:
      - redis
      - aws
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=LOCAL
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_REGION=us-east-1
      - AWS_API_VERSION=2006-03-01
      - AWS_S3_HOST=http://aws:4566
      - AWS_S3_BUCKET=m3-api
      - AWS_ACCESS_KEY_ID=FAKE
      - AWS_SECRET_ACCESS_KEY=FAKE
      - GIT_API_BASE_URL=https://api.github.com
      - GIT_ACCESS_TOKEN=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
    logging:
      options:
        max-size: 50m

  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  aws:
    container_name: aws
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports:
      - 4566-4583:4566-4583
    volumes:
      - "localstack-volume:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack-volume: {}
