service: m3-api

plugins:
  - serverless-localstack
  - serverless-offline
  - serverless-dotenv-plugin
# - serverless-docker-artifacts

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000
  localstack:
    host: http://localhost # optional - LocalStack host to connect to
    edgePort: 4566 # optional - LocalStack edge port to connect to
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 20
  endpointType: REGIONAL
  httpApi:
    cors: true

functions:
  health:
    handler: sls/Lambda.health
    events:
      - http:
          method: get
          path: /health
          cors: true
          timeout: 30
          request:
            parameters:
              querystrings:
                url: true
          response:
            headers:
              Content-Type: "'application/json'"
  data_sync:
    handler: sls/Lambda.getDataSync
    events:
      - http:
          method: post
          path: /data/sync
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
  data_async:
    handler: sls/Lambda.getDataAsync
    events:
      - http:
          method: post
          path: /data/async
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
  callback:
    handler: sls/Lambda.callback
    events:
      - http:
          method: post
          path: /callback
          cors: true
          timeout: 30
          request:
            parameters:
              querystrings:
                url: true
          response:
            headers:
              Content-Type: "'application/json'"