service: dss-api

frameworkVersion: "3"
plugins:
  - serverless-localstack
  - serverless-offline
  - serverless-dotenv-plugin
# - serverless-docker-artifacts

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000
  localstack:
    host: http://localhost # optional - LocalStack host to connect to
    edgePort: 4566         # optional - LocalStack edge port to connect to

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 20
  endpointType: REGIONAL
  httpApi:
    cors: true

functions:
  health:
    handler: sls/Lambda.health
    events:
      - http:
          method: get
          path: /health
          cors: true
          request:
            parameters:
              querystrings:
                url: true
          response:
            headers:
              Content-Type: "'application/json'"
  get_doc:
    handler: sls/Lambda.getDoc
    events:
      - http:
          method: post
          path: /doc
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
  callback:
    handler: sls/Lambda.callback
    events:
      - http:
          method: post
          path: /callback
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"